### PR TITLE
Completed GetLocalIPAddress() in network.go

### PR DESCRIPTION
**Pull request by 0vj**
Completed GetLocalIPAddress() in network.go
issue : [](https://github.com/IEEE-VIT/termiboard/issues/3)

### CODE REVIEW

**Comment by DarthBenro008** [comment]
@mr-tafreshi please resolve your merge conflicts and squash your commits.

**Comment by 0vj** [comment]
Resolved ! :)

**Comment by DarthBenro008** [comment]
Your codebase doesn't seem consistent with the master branch hence the lint is failing, please resolve the lint issues.

**Comment by 0vj** [comment]
I don't think there is a problem with the code. Can you tell me where the problem is?

**Comment by DarthBenro008** [comment]
@mr-tafreshi The code works fine, if you check the ```network.go``` file in the master branch the unused functions are commented out which is not in the case of your commit changes, hence the inconsistency. please make sure everything else is same as master branch except the changes you have made to your function

**Comment by 0vj** [comment]
That is, to use the function I completed?
I just completed the GetLocalIPAddress() in network.go

**Comment by DarthBenro008** [comment]
@mr-tafreshi i am pointing our once again, compare the ```network.go``` file in your branch vs the ```network.go``` file in the master branch, you will find that the unused functions are commented out in the master branch but not in yours. This issue has arised because of improper resolve of the merge conflict encountered before.

**Comment by 0vj** [comment]
Oh. I understood my problem. I have to comment functions of the network.go . it's true ?

**Comment by DarthBenro008** [comment]
Yes, please make sure its consistent with the master branch

**Comment by 0vj** [comment]
Ok. I will close this pr and create new pr

**Pull request closed without merging**
