### PR TITLE
(Bad PR) Implemented GetCpuUsage() function

### PR DESCRIPTION
**Pull request by S-Maciejewski**
This pull request relates to the issue #6 

The GetCpuUsage() method in `cpu.go` was implemented using gopsutil library's cpu.Percent function. The result is displayed by ResultPrinter function as a percentage of overall CPU usage.

### CODE REVIEW

**Comment by DarthBenro008** [comment]
@S-Maciejewski please resolve your merge conflicts.

**Comment by S-Maciejewski** [comment]
> @S-Maciejewski please resolve your merge conflicts.

It is now resolved. However, I am not sure if perhaps the unused function GetCpuTemperature() should be commented out, as I can see golangci-lint having problems with it

**Comment by DarthBenro008** [comment]
Yes , all unused functions must be commented off and the code needs to pass the lint test. Please make the changes accordingly and kindly squash your commits.

**Comment by S-Maciejewski** [comment]
Apologies for the doubled PR, I could not find a way to reopen this after accidentally closing it. Just treat it as spam. Sorry again, I'm still quite new to this kind of workflow

**Pull request closed without merging**
